source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GNZSlidingSegment_Example', :exclusive => true do
  pod "GNZSlidingSegment", :path => "../"
end

target 'GNZSlidingSegment_Tests', :exclusive => true do
  pod "GNZSlidingSegment", :path => "../"

  
end
